# coding: utf-8

"""
    Speech to Text API v3.0

    Speech to Text API v3.0.  # noqa: E501

    OpenAPI spec version: v3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import azure_transcription_client
from azure_transcription_client.models.endpoint_properties import (
    EndpointProperties,
)  # noqa: E501
from azure_transcription_client.rest import ApiException


class TestEndpointProperties(unittest.TestCase):
    """EndpointProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndpointProperties(self):
        """Test EndpointProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = azure_transcription_client.models.endpoint_properties.EndpointProperties()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
