# coding: utf-8

"""
    Speech to Text API v3.0

    Speech to Text API v3.0.  # noqa: E501

    OpenAPI spec version: v3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import azure_transcription_client
from azure_transcription_client.models.api_speechtotext_v30_evaluations_locales_get200_application_json_response import (
    ApiSpeechtotextV30EvaluationsLocalesGet200ApplicationJsonResponse,
)  # noqa: E501
from azure_transcription_client.rest import ApiException


class TestApiSpeechtotextV30EvaluationsLocalesGet200ApplicationJsonResponse(
    unittest.TestCase
):
    """ApiSpeechtotextV30EvaluationsLocalesGet200ApplicationJsonResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiSpeechtotextV30EvaluationsLocalesGet200ApplicationJsonResponse(self):
        """Test ApiSpeechtotextV30EvaluationsLocalesGet200ApplicationJsonResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = azure_transcription_client.models.api_speechtotext_v30_evaluations_locales_get200_application_json_response.ApiSpeechtotextV30EvaluationsLocalesGet200ApplicationJsonResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
