# coding: utf-8

"""
    Speech to Text API v3.0

    Speech to Text API v3.0.  # noqa: E501

    OpenAPI spec version: v3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import azure_transcription_client
from azure_transcription_client.models.model_manifest import ModelManifest  # noqa: E501
from azure_transcription_client.rest import ApiException


class TestModelManifest(unittest.TestCase):
    """ModelManifest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelManifest(self):
        """Test ModelManifest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = azure_transcription_client.models.model_manifest.ModelManifest()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
